alter table INTERSHIP_PRODUCT_IN_STORE add constraint FK_INTERSHIP_PRODUCT_IN_STORE_ON_PRODUCT foreign key (PRODUCT_ID) references INTERSHIP_PRODUCT(ID);
alter table INTERSHIP_PRODUCT_IN_STORE add constraint FK_INTERSHIP_PRODUCT_IN_STORE_ON_SHOP foreign key (SHOP_ID) references INTERSHIP_SHOP(ID);
create index IDX_INTERSHIP_PRODUCT_IN_STORE_ON_PRODUCT on INTERSHIP_PRODUCT_IN_STORE (PRODUCT_ID);
create index IDX_INTERSHIP_PRODUCT_IN_STORE_ON_SHOP on INTERSHIP_PRODUCT_IN_STORE (SHOP_ID);
