alter table INTERSHIP_MANUFACTURER_OF_GOODS add constraint FK_INTERSHIP_MANUFACTURER_OF_GOODS_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create unique index IDX_INTERSHIP_MANUFACTURER_OF_GOODS_UK_NAME on INTERSHIP_MANUFACTURER_OF_GOODS (NAME) where DELETE_TS is null ;
create index IDX_INTERSHIP_MANUFACTURER_OF_GOODS_ON_USER on INTERSHIP_MANUFACTURER_OF_GOODS (USER_ID);
