alter table INTERSHIP_PRICE_HISTORY add constraint FK_INTERSHIP_PRICE_HISTORY_ON_PRODUCT foreign key (PRODUCT_ID) references INTERSHIP_PRODUCT(ID);
alter table INTERSHIP_PRICE_HISTORY add constraint FK_INTERSHIP_PRICE_HISTORY_ON_SHOP foreign key (SHOP_ID) references INTERSHIP_SHOP(ID);
create index IDX_INTERSHIP_PRICE_HISTORY_ON_PRODUCT on INTERSHIP_PRICE_HISTORY (PRODUCT_ID);
create index IDX_INTERSHIP_PRICE_HISTORY_ON_SHOP on INTERSHIP_PRICE_HISTORY (SHOP_ID);
