alter table INTERSHIP_MANUFACTURER_OF_GOODS drop column ADDRESS_HOUSE__U08342 cascade ;
alter table INTERSHIP_MANUFACTURER_OF_GOODS drop column ADDRESS_STREET__U52119 cascade ;
alter table INTERSHIP_MANUFACTURER_OF_GOODS drop column ADDRESS_CITY__U53539 cascade ;
