alter table INTERSHIP_SHOP add constraint FK_INTERSHIP_SHOP_ON_COMMERCIAL_NETWORK foreign key (COMMERCIAL_NETWORK_ID) references INTERSHIP_COMMERCIAL_NETWORK(ID);
create unique index IDX_INTERSHIP_SHOP_UK_NUMBER_ on INTERSHIP_SHOP (NUMBER_) where DELETE_TS is null ;
create index IDX_INTERSHIP_SHOP_ON_COMMERCIAL_NETWORK on INTERSHIP_SHOP (COMMERCIAL_NETWORK_ID);
