alter table INTERSHIP_PURCHASE add constraint FK_INTERSHIP_PURCHASE_ON_BUYER foreign key (BUYER_ID) references INTERSHIP_BUYER(ID);
create index IDX_INTERSHIP_PURCHASE_ON_BUYER on INTERSHIP_PURCHASE (BUYER_ID);
