alter table INTERSHIP_EMPLOYEE add constraint FK_INTERSHIP_EMPLOYEE_ON_SHOP foreign key (SHOP_ID) references INTERSHIP_SHOP(ID);
alter table INTERSHIP_EMPLOYEE add constraint FK_INTERSHIP_EMPLOYEE_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_INTERSHIP_EMPLOYEE_ON_SHOP on INTERSHIP_EMPLOYEE (SHOP_ID);
create index IDX_INTERSHIP_EMPLOYEE_ON_USER on INTERSHIP_EMPLOYEE (USER_ID);
