-- begin INTERSHIP_PRODUCT
alter table INTERSHIP_PRODUCT add constraint FK_INTERSHIP_PRODUCT_ON_MANUFACTURER foreign key (MANUFACTURER_ID) references INTERSHIP_MANUFACTURER_OF_GOODS(ID)^
create unique index IDX_INTERSHIP_PRODUCT_UK_NAME on INTERSHIP_PRODUCT (NAME) where DELETE_TS is null ^
create index IDX_INTERSHIP_PRODUCT_ON_MANUFACTURER on INTERSHIP_PRODUCT (MANUFACTURER_ID)^
-- end INTERSHIP_PRODUCT
-- begin INTERSHIP_COMMERCIAL_NETWORK
create unique index IDX_INTERSHIP_COMMERCIAL_NETWORK_UK_NAME on INTERSHIP_COMMERCIAL_NETWORK (NAME) where DELETE_TS is null ^
-- end INTERSHIP_COMMERCIAL_NETWORK
-- begin INTERSHIP_SHOP
alter table INTERSHIP_SHOP add constraint FK_INTERSHIP_SHOP_ON_COMMERCIAL_NETWORK foreign key (COMMERCIAL_NETWORK_ID) references INTERSHIP_COMMERCIAL_NETWORK(ID)^
create unique index IDX_INTERSHIP_SHOP_UK_NUMBER_ on INTERSHIP_SHOP (NUMBER_) where DELETE_TS is null ^
create index IDX_INTERSHIP_SHOP_ON_COMMERCIAL_NETWORK on INTERSHIP_SHOP (COMMERCIAL_NETWORK_ID)^
-- end INTERSHIP_SHOP
-- begin INTERSHIP_MANUFACTURER_OF_GOODS
alter table INTERSHIP_MANUFACTURER_OF_GOODS add constraint FK_INTERSHIP_MANUFACTURER_OF_GOODS_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create unique index IDX_INTERSHIP_MANUFACTURER_OF_GOODS_UK_NAME on INTERSHIP_MANUFACTURER_OF_GOODS (NAME) where DELETE_TS is null ^
create index IDX_INTERSHIP_MANUFACTURER_OF_GOODS_ON_USER on INTERSHIP_MANUFACTURER_OF_GOODS (USER_ID)^
-- end INTERSHIP_MANUFACTURER_OF_GOODS
