-- begin INTERSHIP_PRODUCT
alter table INTERSHIP_PRODUCT add constraint FK_INTERSHIP_PRODUCT_ON_MANUFACTURER foreign key (MANUFACTURER_ID) references INTERSHIP_MANUFACTURER_OF_GOODS(ID)^
create unique index IDX_INTERSHIP_PRODUCT_UK_NAME on INTERSHIP_PRODUCT (NAME) where DELETE_TS is null ^
create index IDX_INTERSHIP_PRODUCT_ON_MANUFACTURER on INTERSHIP_PRODUCT (MANUFACTURER_ID)^
-- end INTERSHIP_PRODUCT
-- begin INTERSHIP_COMMERCIAL_NETWORK
create unique index IDX_INTERSHIP_COMMERCIAL_NETWORK_UK_NAME on INTERSHIP_COMMERCIAL_NETWORK (NAME) where DELETE_TS is null ^
-- end INTERSHIP_COMMERCIAL_NETWORK
-- begin INTERSHIP_SHOP
alter table INTERSHIP_SHOP add constraint FK_INTERSHIP_SHOP_ON_COMMERCIAL_NETWORK foreign key (COMMERCIAL_NETWORK_ID) references INTERSHIP_COMMERCIAL_NETWORK(ID)^
create unique index IDX_INTERSHIP_SHOP_UK_NUMBER_ on INTERSHIP_SHOP (NUMBER_) where DELETE_TS is null ^
create index IDX_INTERSHIP_SHOP_ON_COMMERCIAL_NETWORK on INTERSHIP_SHOP (COMMERCIAL_NETWORK_ID)^
-- end INTERSHIP_SHOP
-- begin INTERSHIP_MANUFACTURER_OF_GOODS
alter table INTERSHIP_MANUFACTURER_OF_GOODS add constraint FK_INTERSHIP_MANUFACTURER_OF_GOODS_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create unique index IDX_INTERSHIP_MANUFACTURER_OF_GOODS_UK_NAME on INTERSHIP_MANUFACTURER_OF_GOODS (NAME) where DELETE_TS is null ^
create index IDX_INTERSHIP_MANUFACTURER_OF_GOODS_ON_USER on INTERSHIP_MANUFACTURER_OF_GOODS (USER_ID)^
-- end INTERSHIP_MANUFACTURER_OF_GOODS
-- begin INTERSHIP_PRICE_HISTORY
alter table INTERSHIP_PRICE_HISTORY add constraint FK_INTERSHIP_PRICE_HISTORY_ON_PRODUCT foreign key (PRODUCT_ID) references INTERSHIP_PRODUCT(ID)^
alter table INTERSHIP_PRICE_HISTORY add constraint FK_INTERSHIP_PRICE_HISTORY_ON_SHOP foreign key (SHOP_ID) references INTERSHIP_SHOP(ID)^
create index IDX_INTERSHIP_PRICE_HISTORY_ON_PRODUCT on INTERSHIP_PRICE_HISTORY (PRODUCT_ID)^
create index IDX_INTERSHIP_PRICE_HISTORY_ON_SHOP on INTERSHIP_PRICE_HISTORY (SHOP_ID)^
-- end INTERSHIP_PRICE_HISTORY
-- begin INTERSHIP_PRODUCT_IN_PURCHASE
alter table INTERSHIP_PRODUCT_IN_PURCHASE add constraint FK_INTERSHIP_PRODUCT_IN_PURCHASE_ON_PURCHASE foreign key (PURCHASE_ID) references INTERSHIP_PURCHASE(ID)^
alter table INTERSHIP_PRODUCT_IN_PURCHASE add constraint FK_INTERSHIP_PRODUCT_IN_PURCHASE_ON_PRODUCT_IN_STORE foreign key (PRODUCT_IN_STORE_ID) references INTERSHIP_PRODUCT_IN_STORE(ID)^
create index IDX_INTERSHIP_PRODUCT_IN_PURCHASE_ON_PURCHASE on INTERSHIP_PRODUCT_IN_PURCHASE (PURCHASE_ID)^
create index IDX_INTERSHIP_PRODUCT_IN_PURCHASE_ON_PRODUCT_IN_STORE on INTERSHIP_PRODUCT_IN_PURCHASE (PRODUCT_IN_STORE_ID)^
-- end INTERSHIP_PRODUCT_IN_PURCHASE
-- begin INTERSHIP_PRODUCT_IN_STORE
alter table INTERSHIP_PRODUCT_IN_STORE add constraint FK_INTERSHIP_PRODUCT_IN_STORE_ON_PRODUCT foreign key (PRODUCT_ID) references INTERSHIP_PRODUCT(ID)^
alter table INTERSHIP_PRODUCT_IN_STORE add constraint FK_INTERSHIP_PRODUCT_IN_STORE_ON_SHOP foreign key (SHOP_ID) references INTERSHIP_SHOP(ID)^
create index IDX_INTERSHIP_PRODUCT_IN_STORE_ON_PRODUCT on INTERSHIP_PRODUCT_IN_STORE (PRODUCT_ID)^
create index IDX_INTERSHIP_PRODUCT_IN_STORE_ON_SHOP on INTERSHIP_PRODUCT_IN_STORE (SHOP_ID)^
-- end INTERSHIP_PRODUCT_IN_STORE
-- begin INTERSHIP_PURCHASE
alter table INTERSHIP_PURCHASE add constraint FK_INTERSHIP_PURCHASE_ON_SHOP foreign key (SHOP_ID) references INTERSHIP_SHOP(ID)^
alter table INTERSHIP_PURCHASE add constraint FK_INTERSHIP_PURCHASE_ON_BUYER foreign key (BUYER_ID) references INTERSHIP_BUYER(ID)^
create index IDX_INTERSHIP_PURCHASE_ON_SHOP on INTERSHIP_PURCHASE (SHOP_ID)^
create index IDX_INTERSHIP_PURCHASE_ON_BUYER on INTERSHIP_PURCHASE (BUYER_ID)^
-- end INTERSHIP_PURCHASE
-- begin INTERSHIP_BUYER
alter table INTERSHIP_BUYER add constraint FK_INTERSHIP_BUYER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_INTERSHIP_BUYER_ON_USER on INTERSHIP_BUYER (USER_ID)^
-- end INTERSHIP_BUYER
-- begin INTERSHIP_NATURAL_PERSON
alter table INTERSHIP_NATURAL_PERSON add constraint FK_INTERSHIP_NATURAL_PERSON_ON_ID foreign key (ID) references INTERSHIP_BUYER(ID) on delete CASCADE^
-- end INTERSHIP_NATURAL_PERSON
-- begin INTERSHIP_JURIDICAL_PERSON
alter table INTERSHIP_JURIDICAL_PERSON add constraint FK_INTERSHIP_JURIDICAL_PERSON_ON_ID foreign key (ID) references INTERSHIP_BUYER(ID) on delete CASCADE^
-- end INTERSHIP_JURIDICAL_PERSON
-- begin INTERSHIP_EMPLOYEE
alter table INTERSHIP_EMPLOYEE add constraint FK_INTERSHIP_EMPLOYEE_ON_SHOP foreign key (SHOP_ID) references INTERSHIP_SHOP(ID)^
alter table INTERSHIP_EMPLOYEE add constraint FK_INTERSHIP_EMPLOYEE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_INTERSHIP_EMPLOYEE_ON_SHOP on INTERSHIP_EMPLOYEE (SHOP_ID)^
create index IDX_INTERSHIP_EMPLOYEE_ON_USER on INTERSHIP_EMPLOYEE (USER_ID)^
-- end INTERSHIP_EMPLOYEE
